import os
os.system("termux-toast Hello, getting info about phone | termux-vibrate")
os.system("termux-battery-status")
os.system("termux-wifi-scaninfo")
os.system("ifconfig")
os.system("termux-torch on")
os.system("termux-torch off")
os.system("termux-sms-list")
os.system("termux-contact-list")
os.system("termux-call-log")
os.system("termux-notification")
os.system("lscpu")
os.system("ps -A")
os.system("termux-toast Program got info about phone | termux-vibrate")
